assigPro/assigApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [


    url(r'^', views.PersonListView.as_view(), name='person_changelist'),
    url(r'^add/', views.PersonCreateView.as_view(), name='person_add'),
    url(r'^<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    url(r'^ajax/load-cities/$', views.load_cities, name='ajax_load_cities'),

]

assigPro/assigPro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from assigApp import views


urlpatterns = [

 	url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='person_changelist'), name='home'),
	url(r'^hr/', include('assigApp.urls')),
]

assigPro/assigApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)

    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

assigPro/assigApp/forms.py
from django import forms
from .models import Person, City

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

assigPro/assigApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Person, City
from .forms import PersonForm


class PersonListView(ListView):
    model = Person
    context_object_name = 'people'


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')


class           PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'hr/city_dropdown_list_options.html', {'cities': cities})

assigPro/assigApp/templates/assigApp/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

assigPro/assigApp/templates/assigApp/person_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var countryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });
  </script>

{% endblock %}

assigPro/assigApp/templates/assigApp/person_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}


  <p>
    <a href="{% url 'person_add' %}">Add person</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
        <tr>
          <td><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.country.name }}</td>
          <td>{{ person.city.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'person_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

assigPro/templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple ERP{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Simple ERP</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>